# Generated by Django 3.1.6 on 2021-04-15 19:27

from django.db import migrations, models
import manyTAD.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('chromosome', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to=manyTAD.models.get_upload_path)),
                ('resolution', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('data_input_type', models.CharField(default='square', max_length=10)),
                ('norm_ice', models.BooleanField(default=False)),
                ('norm_kr', models.BooleanField(default=False)),
                ('norm_scn', models.BooleanField(default=False)),
                ('norm_vc', models.BooleanField(default=False)),
                ('norm_mcfs', models.BooleanField(default=False)),
                ('clustertad', models.BooleanField(default=False)),
                ('catch', models.BooleanField(default=False)),
                ('arrowhead', models.BooleanField(default=False)),
                ('arrowhead_genomeID', models.CharField(default='hg19', max_length=10)),
                ('topdom', models.BooleanField(default=False)),
                ('topdom_window', models.CharField(default='5', max_length=10)),
                ('armatus', models.BooleanField(default=False)),
                ('armatus_gamma', models.CharField(default='0.2', max_length=10)),
                ('di', models.BooleanField(default=False)),
                ('di_length', models.CharField(default='10', max_length=10)),
                ('spectral', models.BooleanField(default=False)),
                ('chdf', models.BooleanField(default=False)),
                ('gmap', models.BooleanField(default=False)),
                ('ic_finder', models.BooleanField(default=False)),
                ('chromo_r', models.BooleanField(default=False)),
                ('hic_seg', models.BooleanField(default=False)),
                ('hic_explorer', models.BooleanField(default=False)),
                ('insulation', models.BooleanField(default=False)),
                ('insulation_window', models.IntegerField(default=0)),
                ('spectralTAD', models.BooleanField(default=False)),
                ('has_ran', models.BooleanField(default=False)),
            ],
        ),
    ]
